# Generated by Django 4.1.4 on 2022-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name': 'Рецепты', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='dishes',
            name='categoryType',
            field=models.CharField(choices=[('Салаты', 'Салаты'), ('Рецепты первых блюд', 'Рецепты первых блюд'), ('Рецепты вторых блюд', 'Рецепты вторых блюд'), ('Дессерты', 'Дессерты')], max_length=20, verbose_name='Категория'),
        ),
    ]
