# Generated by Django 4.1.7 on 2023-02-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dishes_options_alter_dishes_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='categoryType',
            field=models.CharField(choices=[('Бульоны и супы', 'Бульоны и супы'), ('Горячие блюда', 'Горячие блюда'), ('Салаты', 'Салаты'), ('Закуски', 'Закуски'), ('Выпечка', 'Выпечка'), ('Десерты', 'Десерты')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='recipe',
            field=models.TextField(verbose_name='Текст рецепта'),
        ),
    ]
