# Generated by Django 4.1.7 on 2023-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dishes_categorytype_alter_dishes_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='categoryType',
            field=models.CharField(choices=[('Первые блюда', 'Первые блюда'), ('Вторые блюда', 'Вторые блюда'), ('Салаты', 'Салаты'), ('Десерты', 'Десерты')], max_length=24, verbose_name='Категория'),
        ),
    ]
